---
volumes:
  mailpit_data:
  minio_data:
  redis_data:

services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: comnet
      MINIO_ROOT_PASSWORD: comnetadmin
    command: server /data --console-address ":9001"

  minio_init:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until (mc alias set minio http://minio:9000 comnet comnetadmin 2>/dev/null) do echo '...' && sleep 1; done;
        mc mb --ignore-existing minio/comnet-public;
        mc anonymous set public minio/comnet-public;
        exit 0;
      "

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
